#!/bin/bash
 
NAME="tagged_app"                                  # Name of the application
DJANGODIR=/home/abat/tagged/dj_tagged             # Django project directory
SOCKFILE=/home/abat/tagged/dj_tagged/run/gunicorn.sock  # we will communicte using this unix socket
USER=abat
GROUP=abat
NUM_WORKERS=5                                    # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=TaggedNews.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=TaggedNews.wsgi                     # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
